---
#
# Ansible managed
#
repository:
  description: Install and configure spamassassin on your system.
  homepage: https://robertdebock.nl/
  topics: spamassassin, installer, package, security, ansible, molecule, tox, playbook
