---

- name: test if spamassassin_group is set correctly
  assert:
    that:
      - spamassassin_group is defined
    quiet: yes

- name: test if spamassassin_user is set correctly
  assert:
    that:
      - spamassassin_user is defined
    quiet: yes
