---
# tasks file for spamassassin
- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ spamassassin_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version]
      | default(spamassassin_packages[ansible_distribution]
      | default(spamassassin_packages['default'] )) }}"

- name: create group
  group:
    name: "{{ spamassassin_group}}"
    system: yes

- name: create user
  user:
    name: "{{ spamassassin_user }}"
    group: "{{ spamassassin_group }}"
    comment: Spamassassin user
    system: yes
