---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: spamassassin-ubuntu-artful
    image: ubuntu:artful
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-artful
verifier:
  name: goss
  lint:
    name: yamllint
