---
# handlers file for spamassassin
- name: restart spamassassin
  service:
    name: "{{ spamassassin_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker" or spamassassin_ignore_docker
