---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if connection still works
      ping:

    - name: see if logrotate still works
      command: logrotate /etc/logrotate.d/spamassassin

    - name: see if rsyslog can be restarted
      service:
        name: rsyslog
        state: restarted
