---
# tasks file for core_dependencies
- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ core_dependencies_shared_packages }}"
    - "{{ core_dependencies_packages }}"
  register: core_dependencies_install_packages
  until: core_dependencies_install_packages is succeeded
  retries: 3

- name: try to install pip packages
  pip:
    name: "{{ core_dependencies_pip_packages }}"
    state: present
  register: core_dependencies_install_pip_packages
  until: core_dependencies_install_pip_packages is succeeded
  retries: 3
  failed_when: no
